// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.links */
export type LinksId = number & { __brand: 'LinksId' };

/** Represents the table public.links */
export default interface Links {
  id: LinksId;

  title: string;

  url: string;

  logo: string;
}

/** Represents the initializer for the table public.links */
export interface LinksInitializer {
  /** Default value: nextval('links_id_seq'::regclass) */
  id?: LinksId;

  title: string;

  url: string;

  logo: string;
}

/** Represents the mutator for the table public.links */
export interface LinksMutator {
  id?: LinksId;

  title?: string;

  url?: string;

  logo?: string;
}
