// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.pics */
export type PicsId = number & { __brand: 'PicsId' };

/** Represents the table public.pics */
export default interface Pics {
  id: PicsId;

  name: string;

  url: string;
}

/** Represents the initializer for the table public.pics */
export interface PicsInitializer {
  /** Default value: nextval('pics_id_seq'::regclass) */
  id?: PicsId;

  name: string;

  url: string;
}

/** Represents the mutator for the table public.pics */
export interface PicsMutator {
  id?: PicsId;

  name?: string;

  url?: string;
}
