// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.songs */
export type SongsId = number & { __brand: 'SongsId' };

/** Represents the table public.songs */
export default interface Songs {
  id: SongsId;

  title: string;

  url: string;

  length: number;
}

/** Represents the initializer for the table public.songs */
export interface SongsInitializer {
  /** Default value: nextval('songs_id_seq'::regclass) */
  id?: SongsId;

  title: string;

  url: string;

  length: number;
}

/** Represents the mutator for the table public.songs */
export interface SongsMutator {
  id?: SongsId;

  title?: string;

  url?: string;

  length?: number;
}
