// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SongsId } from './Songs';
import type { AlbumsId } from './Albums';

/** Identifier type for public.tracklist */
export type TracklistId = number & { __brand: 'TracklistId' };

/** Represents the table public.tracklist */
export default interface Tracklist {
  id: TracklistId;

  song_id: SongsId | null;

  album_id: AlbumsId | null;
}

/** Represents the initializer for the table public.tracklist */
export interface TracklistInitializer {
  /** Default value: nextval('tracklist_id_seq'::regclass) */
  id?: TracklistId;

  song_id?: SongsId | null;

  album_id?: AlbumsId | null;
}

/** Represents the mutator for the table public.tracklist */
export interface TracklistMutator {
  id?: TracklistId;

  song_id?: SongsId | null;

  album_id?: AlbumsId | null;
}
