// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.upcoming_shows */
export type UpcomingShowsId = number & { __brand: 'UpcomingShowsId' };

/** Represents the table public.upcoming_shows */
export default interface UpcomingShows {
  id: UpcomingShowsId;

  title: string;

  location: string;

  date: number;
}

/** Represents the initializer for the table public.upcoming_shows */
export interface UpcomingShowsInitializer {
  /** Default value: nextval('upcoming_shows_id_seq'::regclass) */
  id?: UpcomingShowsId;

  title: string;

  location: string;

  date: number;
}

/** Represents the mutator for the table public.upcoming_shows */
export interface UpcomingShowsMutator {
  id?: UpcomingShowsId;

  title?: string;

  location?: string;

  date?: number;
}
